name: EnderCore
version: 0.1
authors: [Zolli]
main: com.Zolli.EnderCore.EnderCore
load: POSTWORLD
softdepend: [PermissionsEx,Permissions,GroupManager,Vault,Essentials,iConomy,BOSEconomy]
commands:
  ec:
    description: Short version of endercore comamnd
  endercore:
    description: Main command for this plugin